/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AttributeGroupTypeResponse } from "./attributegrouptyperesponse";
import { Expose, Type } from "class-transformer";

/**
 * Attribute group type
 */
export enum AttributeGroupSearchResponseAttributeGroupsTypeEnum {
  Workflow = "WORKFLOW",
  Collection = "COLLECTION",
}

export class AttributeGroupSearchResponseAttributeGroups extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: AttributeGroupTypeResponse })
  @Expose({ name: "EditableAttributes" })
  @Type(() => AttributeGroupTypeResponse)
  editableAttributes?: AttributeGroupTypeResponse[];

  @SpeakeasyMetadata()
  @Expose({ name: "ImpactedAttributes" })
  impactedAttributes?: any;

  @SpeakeasyMetadata({ elemType: AttributeGroupTypeResponse })
  @Expose({ name: "ReadOnlyAttributes" })
  @Type(() => AttributeGroupTypeResponse)
  readOnlyAttributes?: AttributeGroupTypeResponse[];

  @SpeakeasyMetadata()
  @Expose({ name: "WorkflowAttributes" })
  workflowAttributes?: any;

  /**
   * 24-character system-generated ID of the attribute group
   */
  @SpeakeasyMetadata()
  @Expose({ name: "_id" })
  id?: string;

  /**
   * Time of attribute group creation (UTC format)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdOn" })
  createdOn?: string;

  /**
   * Accurate description of the attribute and what it represents
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * Time when attribute group was last modified (UTC format)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "modifiedOn" })
  modifiedOn?: string;

  /**
   * Attribute group name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * Priority order of attribute group
   */
  @SpeakeasyMetadata()
  @Expose({ name: "priorityOrder" })
  priorityOrder?: number;

  /**
   * Number of attributes in the attribute group
   */
  @SpeakeasyMetadata()
  @Expose({ name: "totalAttributes" })
  totalAttributes?: number;

  /**
   * Attribute group type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type?: AttributeGroupSearchResponseAttributeGroupsTypeEnum;
}

/**
 * OK
 */
export class AttributeGroupSearchResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: AttributeGroupSearchResponseAttributeGroups })
  @Expose({ name: "attributeGroups" })
  @Type(() => AttributeGroupSearchResponseAttributeGroups)
  attributeGroups?: AttributeGroupSearchResponseAttributeGroups[];

  /**
   * Number of records (attribute group) per page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pageSize" })
  pageSize?: number;

  /**
   * Number of pages for the given `pageSize`
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pages" })
  pages?: number;

  /**
   * Total number of records (attribute group)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "totalSize" })
  totalSize?: number;
}
