/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AttributeResponse } from "./attributeresponse";
import { AttributeValidation } from "./attributevalidation";
import { Expose, Transform, Type } from "class-transformer";

/**
 * OK
 */
export class AttributeMappingResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "attribute" })
  @Type(() => AttributeResponse)
  attribute?: AttributeResponse;

  /**
   * 24-character system-generated attribute ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "attributeId" })
  attributeId?: string;

  /**
   * User ID that created item attribute
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdBy" })
  createdBy?: string;

  /**
   * Time of attribute creation (UTC format)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdOn" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdOn?: Date;

  /**
   * Description for attribute mapping
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * Attribute mapping
   */
  @SpeakeasyMetadata()
  @Expose({ name: "mapping" })
  mapping?: string;

  /**
   * User ID that last modified item attribute
   */
  @SpeakeasyMetadata()
  @Expose({ name: "modifiedBy" })
  modifiedBy?: string;

  /**
   * Time of when the attribute was last modified
   */
  @SpeakeasyMetadata()
  @Expose({ name: "modifiedOn" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  modifiedOn?: Date;

  /**
   * Name of attribute mapping
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * true: Mapping is mandatory; <br> false: mapping is optional
   */
  @SpeakeasyMetadata()
  @Expose({ name: "required" })
  required?: boolean;

  /**
   * Returns attribute mapping for the specified target
   */
  @SpeakeasyMetadata()
  @Expose({ name: "target" })
  target?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "validation" })
  @Type(() => AttributeValidation)
  validation?: AttributeValidation;
}
