/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class AttributeGroupSearchRequestInclude extends SpeakeasyBase {
  /**
   * true: Includes attributes <br> false: Excludes attributes
   */
  @SpeakeasyMetadata()
  @Expose({ name: "attributes" })
  attributes?: boolean;
}

export class AttributeGroupSearchRequestMatchOr extends SpeakeasyBase {
  /**
   * Attribute group name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

export class AttributeGroupSearchRequestMatch extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: AttributeGroupSearchRequestMatchOr })
  @Expose({ name: "or" })
  @Type(() => AttributeGroupSearchRequestMatchOr)
  or?: AttributeGroupSearchRequestMatchOr[];

  /**
   * Search target. Currently, supports only ITEM.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "target" })
  target?: string;
}

/**
 * Direction (ascending or descending) or sorting the response
 */
export enum AttributeGroupSearchRequestSortDirectionEnum {
  Asc = "ASC",
  Desc = "DESC",
}

export class AttributeGroupSearchRequestSort extends SpeakeasyBase {
  /**
   * Direction (ascending or descending) or sorting the response
   */
  @SpeakeasyMetadata()
  @Expose({ name: "direction" })
  direction?: AttributeGroupSearchRequestSortDirectionEnum;

  /**
   * Field on which the results must be sorted
   */
  @SpeakeasyMetadata()
  @Expose({ name: "field" })
  field?: string;
}

export class AttributeGroupSearchRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "include" })
  @Type(() => AttributeGroupSearchRequestInclude)
  include?: AttributeGroupSearchRequestInclude;

  @SpeakeasyMetadata()
  @Expose({ name: "match" })
  @Type(() => AttributeGroupSearchRequestMatch)
  match?: AttributeGroupSearchRequestMatch;

  /**
   * Page number to be retrieved
   */
  @SpeakeasyMetadata()
  @Expose({ name: "page" })
  page?: number;

  /**
   * Number of records (attribute groups) per page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "size" })
  size?: number;

  @SpeakeasyMetadata({ elemType: AttributeGroupSearchRequestSort })
  @Expose({ name: "sort" })
  @Type(() => AttributeGroupSearchRequestSort)
  sort?: AttributeGroupSearchRequestSort[];
}
