/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AttributeValidation } from "./attributevalidation";
import { Expose, Type } from "class-transformer";

export class AttributeMappingModifyMappings extends SpeakeasyBase {
  /**
   * Attribute ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "attributeId" })
  attributeId?: string;

  /**
   * Description of the attribute mapping
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * Attribute mapping
   */
  @SpeakeasyMetadata()
  @Expose({ name: "mapping" })
  mapping?: string;

  /**
   * Name of the attribute mapping
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * true: Mapping is mandatory <br> false: Mapping is optional
   */
  @SpeakeasyMetadata()
  @Expose({ name: "required" })
  required?: boolean;

  @SpeakeasyMetadata()
  @Expose({ name: "validation" })
  @Type(() => AttributeValidation)
  validation?: AttributeValidation;
}

export class AttributeMappingModify extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: AttributeMappingModifyMappings })
  @Expose({ name: "mappings" })
  @Type(() => AttributeMappingModifyMappings)
  mappings?: AttributeMappingModifyMappings[];
}
