/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Specification for matching attribute mapping.
 */
export class AttributeMappingMatch extends SpeakeasyBase {
  /**
   * 24-character system-generated Attribute ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "attributeId" })
  attributeId?: string;

  /**
   * Mapping for an attribute whose description contains the specified value.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * Attribute mapping
   */
  @SpeakeasyMetadata()
  @Expose({ name: "mapping" })
  mapping?: string;

  /**
   * Mapping for an attribute whose name contains the specified value
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * true: Returns only the attribute mappings that are mandatory
   */
  @SpeakeasyMetadata()
  @Expose({ name: "required" })
  required?: boolean;

  /**
   * Attribute mapping for the specified target
   */
  @SpeakeasyMetadata()
  @Expose({ name: "target" })
  target?: string;
}
