/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AttributeGroupTypeRequest } from "./attributegrouptyperequest";
import { Expose, Type } from "class-transformer";

/**
 * Action type. For `CREATE`, 'priorityOrder', 'type', 'name,' and 'editableAttributes' are mandatory. For `UPDATE` and `DELETE`, only `id` is mandatory.
 */
export enum AttributeGroupRequestAttributeGroupActionEnum {
  Create = "CREATE",
  Update = "UPDATE",
  Delete = "DELETE",
}

/**
 * Type of attribute group
 */
export enum AttributeGroupRequestAttributeGroupTypeEnum {
  Workflow = "WORKFLOW",
  Collection = "COLLECTION",
}

export class AttributeGroupRequestAttributeGroup extends SpeakeasyBase {
  /**
   * Action type. For `CREATE`, 'priorityOrder', 'type', 'name,' and 'editableAttributes' are mandatory. For `UPDATE` and `DELETE`, only `id` is mandatory.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "action" })
  action?: AttributeGroupRequestAttributeGroupActionEnum;

  /**
   * Accurate description of attribute and what it represents
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  @SpeakeasyMetadata({ elemType: AttributeGroupTypeRequest })
  @Expose({ name: "editableAttributes" })
  @Type(() => AttributeGroupTypeRequest)
  editableAttributes?: AttributeGroupTypeRequest[];

  /**
   * 24-character system-generated attribute group ID. Applicable only for `UPDATE` and `DELETE` actions. To be omitted for 'CREATE'.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Attribute group nam
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * Attribute groups can be assigned a priority order. This is used for  attributes that are under multiple attribute groups. They will be returned just once in the attribute group that has the highest priority. <br> **Note**: Mandatory attribute for 'CREATE', must be unique and start from 0 for the first group.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "priorityOrder" })
  priorityOrder?: number;

  /**
   * Type of attribute group
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type?: AttributeGroupRequestAttributeGroupTypeEnum;
}

export class AttributeGroupRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: AttributeGroupRequestAttributeGroup })
  @Expose({ name: "attributeGroup" })
  @Type(() => AttributeGroupRequestAttributeGroup)
  attributeGroup?: AttributeGroupRequestAttributeGroup[];

  /**
   * true: All updates succeed or fail as a unit <br> false: Some can succeed or fail
   */
  @SpeakeasyMetadata()
  @Expose({ name: "transactional" })
  transactional: boolean;
}
