/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class AttributeGroupResponseAttributes extends SpeakeasyBase {
  /**
   * 24-character system-generated attribute ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "_id" })
  id?: string;

  /**
   * 24-character system-generated attribute group ID of items
   */
  @SpeakeasyMetadata()
  @Expose({ name: "attributeGroupId" })
  attributeGroupId?: string;

  /**
   * 24-character system-generated attribute ID. This is same as the `_id`.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "attributeId" })
  attributeId?: string;

  /**
   * Time of attribute creation (UTC format)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdOn" })
  createdOn?: string;

  /**
   * true: Attribute is editable <br> false: Attribute is non-editable
   */
  @SpeakeasyMetadata()
  @Expose({ name: "isEditable" })
  isEditable?: boolean;

  /**
   * Time of when attribute was last modified (UTC format).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "modifiedOn" })
  modifiedOn?: string;

  /**
   * Order of item within the attribute group
   */
  @SpeakeasyMetadata()
  @Expose({ name: "order" })
  order?: number;
}

/**
 * Attribute group type
 */
export enum AttributeGroupResponseTypeEnum {
  Workflow = "WORKFLOW",
  Collection = "COLLECTION",
}

export class AttributeGroupResponse extends SpeakeasyBase {
  /**
   * 24-character system-generated attribute group ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "_id" })
  id?: string;

  @SpeakeasyMetadata({ elemType: AttributeGroupResponseAttributes })
  @Expose({ name: "attributes" })
  @Type(() => AttributeGroupResponseAttributes)
  attributes?: AttributeGroupResponseAttributes[];

  /**
   * Time of attribute group creation (UTC format).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdOn" })
  createdOn?: string;

  /**
   * Accurate description of attribute group and what it represents
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * Time when attribute group was last modified (UTC format).
   */
  @SpeakeasyMetadata()
  @Expose({ name: "modifiedOn" })
  modifiedOn?: string;

  /**
   * Attribute group name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * Order of priority of the attribute group
   */
  @SpeakeasyMetadata()
  @Expose({ name: "priorityOrder" })
  priorityOrder?: number;

  /**
   * Attribute group type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type?: AttributeGroupResponseTypeEnum;
}
