/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class AttributeValueFrenchLocale extends SpeakeasyBase {
  /**
   * Attribute name in French
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * Attribute value in French
   */
  @SpeakeasyMetadata()
  @Expose({ name: "value" })
  value?: string;
}
