/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AttributeMappingResponse } from "./attributemappingresponse";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class AttributeMappingPaginationResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: AttributeMappingResponse })
  @Expose({ name: "mappings" })
  @Type(() => AttributeMappingResponse)
  mappings?: AttributeMappingResponse[];

  /**
   * Number of records in a page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pageSize" })
  pageSize?: number;

  /**
   * Total number of pages in the response
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pages" })
  pages?: number;

  /**
   * Total number of records
   */
  @SpeakeasyMetadata()
  @Expose({ name: "totalSize" })
  totalSize?: number;
}
