/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Action type. <br> **Note**: <br> 1) Attribute ID is required only for `UPDATE` and `DELETE` actions (not for CREATE). <br> 2) The Create action replaces any existing category attribute with the same name.
 */
export enum AttributeGroupTypeRequestActionEnum {
  Add = "ADD",
  Update = "UPDATE",
  Delete = "DELETE",
}

export class AttributeGroupTypeRequest extends SpeakeasyBase {
  /**
   * Action type. <br> **Note**: <br> 1) Attribute ID is required only for `UPDATE` and `DELETE` actions (not for CREATE). <br> 2) The Create action replaces any existing category attribute with the same name.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "action" })
  action?: AttributeGroupTypeRequestActionEnum;

  /**
   * 24-character system-generated ID of item attribute
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Order of item attributes within the attribute group. Relevant for sorting in the UI.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "order" })
  order?: number;
}
