/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class BulkAttributeResponseAttributesFailed extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "errors" })
  errors?: string[];

  /**
   * Failure reason as stored backend
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

export class BulkAttributeResponseAttributesSuccess extends SpeakeasyBase {
  /**
   * 24-character system-generated attribute ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Success message
   */
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;

  /**
   * Attribute name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

export class BulkAttributeResponseAttributes extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: BulkAttributeResponseAttributesFailed })
  @Expose({ name: "failed" })
  @Type(() => BulkAttributeResponseAttributesFailed)
  failed?: BulkAttributeResponseAttributesFailed[];

  @SpeakeasyMetadata({ elemType: BulkAttributeResponseAttributesSuccess })
  @Expose({ name: "success" })
  @Type(() => BulkAttributeResponseAttributesSuccess)
  success?: BulkAttributeResponseAttributesSuccess[];
}

/**
 * OK
 */
export class BulkAttributeResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "attributes" })
  @Type(() => BulkAttributeResponseAttributes)
  attributes?: BulkAttributeResponseAttributes;
}
