/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Action type
 */
export enum BundleUpdateRequestActionEnum {
  Update = "UPDATE",
}

/**
 * Action type
 */
export enum BundleUpdateRequestBundlesActionEnum {
  Set = "SET",
  Unset = "UNSET",
}

export class BundleUpdateRequestBundles extends SpeakeasyBase {
  /**
   * Action type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "action" })
  action: BundleUpdateRequestBundlesActionEnum;

  /**
   * Stock Keeping Unit (SKU) of bundle
   */
  @SpeakeasyMetadata()
  @Expose({ name: "bundleSku" })
  bundleSku: string;

  /**
   * Stock Keeping Unit (SKU) of item
   */
  @SpeakeasyMetadata()
  @Expose({ name: "itemSku" })
  itemSku: string;

  /**
   * Item quantity
   */
  @SpeakeasyMetadata()
  @Expose({ name: "quantity" })
  quantity?: number;
}

export class BundleUpdateRequest extends SpeakeasyBase {
  /**
   * Action type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "action" })
  action?: BundleUpdateRequestActionEnum;

  @SpeakeasyMetadata({ elemType: BundleUpdateRequestBundles })
  @Expose({ name: "bundles" })
  @Type(() => BundleUpdateRequestBundles)
  bundles?: BundleUpdateRequestBundles[];
}
