/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class BundleUpdateResponse extends SpeakeasyBase {
  /**
   * 24-character system-generated bundle ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "bundleId" })
  bundleId?: string;

  /**
   * Time of bundle creation (UTC format)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdOn" })
  createdOn?: string;

  /**
   * 24-character system-generated document ID (internal only)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * 24-character system-generated item ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "itemId" })
  itemId?: string;

  /**
   * Time when bundle was last updated (UTC format)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "modifiedOn" })
  modifiedOn?: string;

  /**
   * Bundle quantity
   */
  @SpeakeasyMetadata()
  @Expose({ name: "quantity" })
  quantity?: number;
}
