/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class BundleItems extends SpeakeasyBase {
  /**
   * Item quantity to be added to bundle
   */
  @SpeakeasyMetadata()
  @Expose({ name: "quantity" })
  quantity: number;

  /**
   * Stock Keeping Unit (SKU) of item that must be added to bundle
   */
  @SpeakeasyMetadata()
  @Expose({ name: "sku" })
  sku: string;
}
