/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Attribute } from "./attribute";
import { Breadcrumbs } from "./breadcrumbs";
import { Expose, Type } from "class-transformer";

export class CategoryChild extends SpeakeasyBase {
  /**
   * List of attributes and their details
   */
  @SpeakeasyMetadata({ elemType: Attribute })
  @Expose({ name: "attributes" })
  @Type(() => Attribute)
  attributes?: Attribute[];

  /**
   * Path of categories leading to root of categories
   */
  @SpeakeasyMetadata({ elemType: Breadcrumbs })
  @Expose({ name: "breadcrumbs" })
  @Type(() => Breadcrumbs)
  breadcrumbs?: Breadcrumbs[];

  /**
   * Details of children categories
   */
  @SpeakeasyMetadata({ elemType: CategoryChild })
  @Expose({ name: "children" })
  @Type(() => CategoryChild)
  children?: CategoryChild[];

  /**
   * 24-character system-generated category ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Category name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}
