/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Action type
 */
export enum CategoryItemAttributeConditionsRequestItemAttributeConditionsActionEnum {
  Set = "SET",
  Unset = "UNSET",
}

/**
 * Applicable criteria
 */
export enum CategoryItemAttributeConditionsRequestItemAttributeConditionsConditionTypeEnum {
  Yes = "YES",
  No = "NO",
  Contains = "CONTAINS",
  DoesNotContain = "DOES_NOT_CONTAIN",
  IsExactMatch = "IS_EXACT_MATCH",
  IsEqualTo = "IS_EQUAL_TO",
  IsGreaterThan = "IS_GREATER_THAN",
  IsLessThan = "IS_LESS_THAN",
  Includes = "INCLUDES",
  Excludes = "EXCLUDES",
}

export class CategoryItemAttributeConditionsRequestItemAttributeConditionsCondition extends SpeakeasyBase {
  /**
   * Applicable criteria
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: CategoryItemAttributeConditionsRequestItemAttributeConditionsConditionTypeEnum;

  /**
   * Value corresponding to condition `type`
   */
  @SpeakeasyMetadata()
  @Expose({ name: "value" })
  value?: string;
}

export class CategoryItemAttributeConditionsRequestItemAttributeConditions extends SpeakeasyBase {
  /**
   * Action type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "action" })
  action: CategoryItemAttributeConditionsRequestItemAttributeConditionsActionEnum;

  /**
   * 24-character system-generated attribute ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "attributeId" })
  attributeId: string;

  @SpeakeasyMetadata()
  @Expose({ name: "condition" })
  @Type(
    () => CategoryItemAttributeConditionsRequestItemAttributeConditionsCondition
  )
  condition?: CategoryItemAttributeConditionsRequestItemAttributeConditionsCondition;
}

export class CategoryItemAttributeConditionsRequest extends SpeakeasyBase {
  /**
   * 24-character system-generated category ID. `nodeId` and `id` are the two identifier of a category, and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Details of conditions set or unset
   */
  @SpeakeasyMetadata({
    elemType: CategoryItemAttributeConditionsRequestItemAttributeConditions,
  })
  @Expose({ name: "itemAttributeConditions" })
  @Type(() => CategoryItemAttributeConditionsRequestItemAttributeConditions)
  itemAttributeConditions?: CategoryItemAttributeConditionsRequestItemAttributeConditions[];

  /**
   * Human-readable numeric ID of category. `nodeId` and `id` are the two identifier of a category, and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: number;
}
