/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Attribute type
 */
export enum CategoryItemAttributeTypeEnum {
  Text = "TEXT",
  Boolean = "BOOLEAN",
  Serial = "SERIAL",
  Decimal = "DECIMAL",
  Integer = "INTEGER",
  Datetime = "DATETIME",
}

export class CategoryItemAttribute extends SpeakeasyBase {
  /**
   * 24-character system-generated attribute ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Attribute name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * true: Attribute is mandatory <br> false: Attribute is optional
   */
  @SpeakeasyMetadata()
  @Expose({ name: "required" })
  required?: boolean;

  /**
   * Attribute type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type?: CategoryItemAttributeTypeEnum;
}
