/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CategoryAttribute } from "./categoryattribute";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class CategoryAttributes extends SpeakeasyBase {
  /**
   * List of attributes and their details
   */
  @SpeakeasyMetadata({ elemType: CategoryAttribute })
  @Expose({ name: "attributes" })
  @Type(() => CategoryAttribute)
  attributes?: CategoryAttribute[];

  /**
   * 24-character system-generated category ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Category name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * Human-readable numeric category ID, for external users
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: number;
}
