/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CategorySingle } from "./categorysingle";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class CategoryPage extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: CategorySingle })
  @Expose({ name: "categories" })
  @Type(() => CategorySingle)
  categories?: CategorySingle[];

  /**
   * Number of records (categories) per page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pageSize" })
  pageSize?: number;

  /**
   * Number of pages for the given `pageSize`
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pages" })
  pages?: number;

  /**
   * Total number of records (categories)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "totalSize" })
  totalSize?: number;
}
