/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CategoryItemAttribute } from "./categoryitemattribute";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class CategoryItemAttributes extends SpeakeasyBase {
  /**
   * 24-character system-generated category ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  @SpeakeasyMetadata({ elemType: CategoryItemAttribute })
  @Expose({ name: "itemAttributes" })
  @Type(() => CategoryItemAttribute)
  itemAttributes?: CategoryItemAttribute[];

  /**
   * Category name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * Human-readable numeric ID of category, for external users
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: number;
}
