/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Client error
 */
export class ClientError extends SpeakeasyBase {
  /**
   * Error code for machine consumption
   */
  @SpeakeasyMetadata()
  @Expose({ name: "code" })
  code?: string;

  /**
   * Human-readable error description
   */
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;
}
