/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class FileSearchRequest extends SpeakeasyBase {
  /**
   * Page number to be retrieved. <br> **Note**: <br> 1) Applicable only in a paginated response. <br> 2) Always paired with `size`
   */
  @SpeakeasyMetadata()
  @Expose({ name: "page" })
  page?: number;

  /**
   * Number of records (attribute groups) per page <br> **Note**: <br> 1) Applicable only in a paginated response. <br> 2) Always paired with `page`
   */
  @SpeakeasyMetadata()
  @Expose({ name: "size" })
  size?: any;
}
