/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { FileResponse } from "./fileresponse";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class FilePaginationResponse extends SpeakeasyBase {
  /**
   * List of files and their details
   */
  @SpeakeasyMetadata({ elemType: FileResponse })
  @Expose({ name: "files" })
  @Type(() => FileResponse)
  files?: FileResponse[];

  /**
   * Number of records (bundle) in a page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pageSize" })
  pageSize?: number;

  /**
   * Number of pages for the given `pageSize`
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pages" })
  pages?: number;

  /**
   * Total number of records
   */
  @SpeakeasyMetadata()
  @Expose({ name: "totalSize" })
  totalSize?: number;
}
