/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class GetCategoryItemAttributesItemAttributes extends SpeakeasyBase {
  /**
   * 24-character system-generated attribute ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * If this attribute is mapped to one of the standard names used by PIM, this is the name the attribute is mapped to.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "mapping" })
  mapping?: string;

  /**
   * Attribute name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * true: Attribute is mandatory <br> false: Attribute is optional
   */
  @SpeakeasyMetadata()
  @Expose({ name: "required" })
  required?: boolean;

  /**
   * Attribute type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type?: string;
}

/**
 * OK
 */
export class GetCategoryItemAttributes extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: GetCategoryItemAttributesItemAttributes })
  @Expose({ name: "itemAttributes" })
  @Type(() => GetCategoryItemAttributesItemAttributes)
  itemAttributes?: GetCategoryItemAttributesItemAttributes[];

  /**
   * Number of records in a page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pageSize" })
  pageSize?: number;

  /**
   * Number of pages for the given `pageSize`
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pages" })
  pages?: number;

  /**
   * Total number of records
   */
  @SpeakeasyMetadata()
  @Expose({ name: "totalSize" })
  totalSize?: number;
}
