/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * OK
 */
export class GetS3URLItemAttributeResponse extends SpeakeasyBase {
  /**
   * 24-character system-generated file ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "fileId" })
  fileId?: string;

  /**
   * S3 key of the file
   */
  @SpeakeasyMetadata()
  @Expose({ name: "key" })
  key?: string;

  /**
   * S3 bucket url, to upload the template file.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "url" })
  url?: string;
}
