/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class GetS3URLItemAttributeRequest extends SpeakeasyBase {
  /**
   * File name to be uploaded in the generated URL
   */
  @SpeakeasyMetadata()
  @Expose({ name: "fileName" })
  fileName?: string;
}
