/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Action to set or unset (remove) the inherited attribute
 */
export enum InheritItemAttributesUpdateActionEnum {
  Set = "SET",
  Unset = "UNSET",
}

export class InheritItemAttributesUpdate extends SpeakeasyBase {
  /**
   * Action to set or unset (remove) the inherited attribute
   */
  @SpeakeasyMetadata()
  @Expose({ name: "action" })
  action: InheritItemAttributesUpdateActionEnum;

  /**
   * Name of the attribute that can be inherited
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;
}
