/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Product } from "./product";
import { Expose, Type } from "class-transformer";

export class ItemProductsResponse extends SpeakeasyBase {
  /**
   * Number of records (items) in a page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pageSize" })
  pageSize?: number;

  /**
   * Number of pages for the given `pageSize`
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pages" })
  pages?: number;

  @SpeakeasyMetadata({ elemType: Product })
  @Expose({ name: "products" })
  @Type(() => Product)
  products?: Product[];

  /**
   * Total number of records (items)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "totalSize" })
  totalSize?: number;
}
