/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ProductSearch } from "./productsearch";
import { Expose, Type } from "class-transformer";

export class ItemProductSearchResponse extends SpeakeasyBase {
  /**
   * Number of records per page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pageSize" })
  pageSize?: number;

  /**
   * Number of pages for the given pageSize
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pages" })
  pages?: number;

  @SpeakeasyMetadata({ elemType: ProductSearch })
  @Expose({ name: "products" })
  @Type(() => ProductSearch)
  products?: ProductSearch[];

  /**
   * Total number of records
   */
  @SpeakeasyMetadata()
  @Expose({ name: "totalSize" })
  totalSize?: number;
}
