/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * OK
 */
export class ModifyCategory extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "attributes" })
  attributes?: Record<string, any>[];

  /**
   * Path of categories leading to root of category
   */
  @SpeakeasyMetadata()
  @Expose({ name: "breadcrumbs" })
  breadcrumbs?: Record<string, any>[];

  @SpeakeasyMetadata()
  @Expose({ name: "children" })
  children?: Record<string, any>[];

  /**
   * Time of category creation (UTC format)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdOn" })
  createdOn?: string;

  /**
   * 24-character system-generated category ID. `nodeId` and `id` are the two identifier of a category, and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Time when category was last updated (UTC format)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "modifiedOn" })
  modifiedOn?: string;

  /**
   * Category name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * Human-readable numeric ID of category. `nodeId` and `id` are the two identifier of a category, and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: number;
}
