/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ModifyCategoryRequest extends SpeakeasyBase {
  /**
   * true: Category is Active <br> false: Category is Inactive <br> **Note**: Inactive status is not applicable for Primary category.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "active" })
  active?: boolean;

  /**
   * Category name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * Position of this category amongst sibling categories within the same parent category
   */
  @SpeakeasyMetadata()
  @Expose({ name: "order" })
  order?: number;

  /**
   * Human-readable numeric ID of parent category, for external users
   */
  @SpeakeasyMetadata()
  @Expose({ name: "parentNodeId" })
  parentNodeId?: number;
}
