/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Action type
 */
export enum ModifyCategoryAttributesRequestAttributesActionEnum {
  Set = "SET",
  Unset = "UNSET",
}

export class ModifyCategoryAttributesRequestAttributes extends SpeakeasyBase {
  /**
   * Action type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "action" })
  action: ModifyCategoryAttributesRequestAttributesActionEnum;

  /**
   * 24-character system-generated attribute ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "attributeId" })
  attributeId: string;

  @SpeakeasyMetadata()
  @Expose({ name: "value" })
  value?: any;
}

export class ModifyCategoryAttributesRequest extends SpeakeasyBase {
  /**
   * Details of category attributes
   */
  @SpeakeasyMetadata({ elemType: ModifyCategoryAttributesRequestAttributes })
  @Expose({ name: "attributes" })
  @Type(() => ModifyCategoryAttributesRequestAttributes)
  attributes: ModifyCategoryAttributesRequestAttributes[];

  /**
   * 24-character system-generated category ID. `nodeId` and `id` are the two identifier of a category, and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Human-readable numeric ID of category. `nodeId` and `id` are the two identifier of a category, and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: number;
}
