/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Action type
 */
export enum ModifyNodeSourcesRequestSourcesActionEnum {
  Set = "SET",
  Unset = "UNSET",
}

export class ModifyNodeSourcesRequestSources extends SpeakeasyBase {
  /**
   * Action type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "action" })
  action?: ModifyNodeSourcesRequestSourcesActionEnum;

  /**
   * 24-character system-generated category ID. `nodeId` and `id` are the two identifiers of a category and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Human-readable numeric ID of category. `nodeId` and `id` are the two identifiers of a category and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: number;
}

export class ModifyNodeSourcesRequest extends SpeakeasyBase {
  /**
   * 24-character system-generated category ID. `nodeId` and `id` are the two identifier of a category, and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Human-readable numeric ID of category. `nodeId` and `id` are the two identifier of a category, and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: number;

  @SpeakeasyMetadata({ elemType: ModifyNodeSourcesRequestSources })
  @Expose({ name: "sources" })
  @Type(() => ModifyNodeSourcesRequestSources)
  sources?: ModifyNodeSourcesRequestSources[];
}
