/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Action type
 */
export enum ModifyCategoryItemAttributesRequestItemAttributesActionEnum {
  Set = "SET",
  Unset = "UNSET",
}

export class ModifyCategoryItemAttributesRequestItemAttributes extends SpeakeasyBase {
  /**
   * Action type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "action" })
  action: ModifyCategoryItemAttributesRequestItemAttributesActionEnum;

  /**
   * 24-character system-generated attribute ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "attributeId" })
  attributeId: string;

  /**
   * true: Attribute is mandatory <br> false: Attribute is optional
   */
  @SpeakeasyMetadata()
  @Expose({ name: "mandatory" })
  mandatory?: boolean;
}

export class ModifyCategoryItemAttributesRequest extends SpeakeasyBase {
  /**
   * 24-character system-generated category ID. `nodeId` and `id` are the two identifier of a category, and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Item attributes within a category
   */
  @SpeakeasyMetadata({
    elemType: ModifyCategoryItemAttributesRequestItemAttributes,
  })
  @Expose({ name: "itemAttributes" })
  @Type(() => ModifyCategoryItemAttributesRequestItemAttributes)
  itemAttributes: ModifyCategoryItemAttributesRequestItemAttributes[];

  /**
   * Human-readable numeric ID of category. `nodeId` and `id` are the two identifier of a category, and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: number;
}
