/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class NodeSourceExclusionsSourceExclusions extends SpeakeasyBase {
  /**
   * Path leading to source of category
   */
  @SpeakeasyMetadata()
  @Expose({ name: "breadcrumbString" })
  breadcrumbString?: string;

  /**
   * 24-character system-generated category ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Category name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * Human-readable numeric ID of category, for external users
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: number;
}

/**
 * OK
 */
export class NodeSourceExclusions extends SpeakeasyBase {
  /**
   * 24-character system-generated category ID.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Category name
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * Human-readable numeric ID of category, for external users
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: number;

  /**
   * Number of records (categories) in a page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pageSize" })
  pageSize?: number;

  /**
   * Number of pages for the given `pageSize`
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pages" })
  pages?: number;

  @SpeakeasyMetadata({ elemType: NodeSourceExclusionsSourceExclusions })
  @Expose({ name: "sourceExclusions" })
  @Type(() => NodeSourceExclusionsSourceExclusions)
  sourceExclusions?: NodeSourceExclusionsSourceExclusions[];

  /**
   * Total number of records
   */
  @SpeakeasyMetadata()
  @Expose({ name: "totalSize" })
  totalSize?: number;
}
