/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Action type
 */
export enum NodeSourcesAndExclusionsRequestSourceExclusionsActionEnum {
  Set = "SET",
  Unset = "UNSET",
}

export class NodeSourcesAndExclusionsRequestSourceExclusions extends SpeakeasyBase {
  /**
   * Action type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "action" })
  action?: NodeSourcesAndExclusionsRequestSourceExclusionsActionEnum;

  /**
   * 24-character system-generated category ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Human-readable numeric ID of category, for external users
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: number;
}

export class NodeSourcesAndExclusionsRequest extends SpeakeasyBase {
  /**
   * 24-character system-generated category ID. `nodeId` and `id` are the two identifier of a category, and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Human-readable numeric ID of category. `nodeId` and `id` are the two identifier of a category, and one of them must be specified.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: number;

  @SpeakeasyMetadata({
    elemType: NodeSourcesAndExclusionsRequestSourceExclusions,
  })
  @Expose({ name: "sourceExclusions" })
  @Type(() => NodeSourcesAndExclusionsRequestSourceExclusions)
  sourceExclusions?: NodeSourcesAndExclusionsRequestSourceExclusions[];
}
