/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ProductAttribute } from "./productattribute";
import { ProductCategory } from "./productcategory";
import { Expose, Type } from "class-transformer";

export class ProductV2 extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: ProductAttribute })
  @Expose({ name: "attributes" })
  @Type(() => ProductAttribute)
  attributes?: ProductAttribute[];

  @SpeakeasyMetadata({ elemType: ProductCategory })
  @Expose({ name: "categories" })
  @Type(() => ProductCategory)
  categories?: ProductCategory[];

  /**
   * Number of children or variants of the item
   */
  @SpeakeasyMetadata()
  @Expose({ name: "childrenSize" })
  childrenSize?: number;

  /**
   * Item ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "itemId" })
  itemId?: number;

  /**
   * Stock Keeping Unit (SKU) of item
   */
  @SpeakeasyMetadata()
  @Expose({ name: "sku" })
  sku?: string;

  /**
   * true: Item is Active <br> false: Item is Inactive
   */
  @SpeakeasyMetadata()
  @Expose({ name: "status" })
  status?: boolean;

  /**
   * Item type - ITEM or BUNDLE
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type?: string;
}
