/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ProductResponse } from "./productresponse";
import { Expose, Type } from "class-transformer";

/**
 * Error code for backend mapping
 */
export enum ProductModifyErrorCodeEnum {
  StatusError = "STATUS_ERROR",
}

export class ProductModifyErrorMessage extends SpeakeasyBase {
  /**
   * Index of the item update request
   */
  @SpeakeasyMetadata()
  @Expose({ name: "index" })
  index?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "item" })
  @Type(() => ProductResponse)
  item?: ProductResponse;
}

/**
 * Failing items
 */
export class ProductModifyError extends SpeakeasyBase {
  /**
   * Error code for backend mapping
   */
  @SpeakeasyMetadata()
  @Expose({ name: "code" })
  code?: ProductModifyErrorCodeEnum;

  /**
   * Error details for invalid items
   */
  @SpeakeasyMetadata({ elemType: ProductModifyErrorMessage })
  @Expose({ name: "message" })
  @Type(() => ProductModifyErrorMessage)
  message?: ProductModifyErrorMessage[];
}
