/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { InheritItemAttributesUpdate } from "./inherititemattributesupdate";
import { Expose, Type } from "class-transformer";

export class ProductUpdate extends SpeakeasyBase {
  /**
   * Action type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "action" })
  action?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "attributeValues" })
  attributeValues?: any[];

  @SpeakeasyMetadata({ elemType: InheritItemAttributesUpdate })
  @Expose({ name: "inheritedAttributes" })
  @Type(() => InheritItemAttributesUpdate)
  inheritedAttributes?: InheritItemAttributesUpdate[];

  /**
   * Stock Keeping Unit (SKU) of parent item
   */
  @SpeakeasyMetadata()
  @Expose({ name: "parentSku" })
  parentSku?: string;

  /**
   * List of Stock Keeping Units (SKUs)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "skus" })
  skus?: string[];

  /**
   * Item type - Bundle or Item
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type?: string;
}
