/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class ProductResponseFailed extends SpeakeasyBase {
  /**
   * Failure message
   */
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;

  /**
   * Stock Keeping Unit (SKU), a unique identifier of item
   */
  @SpeakeasyMetadata()
  @Expose({ name: "sku" })
  sku?: string;
}

export class ProductResponseSuccessErrorAttributes extends SpeakeasyBase {
  /**
   * Human-readable error message
   */
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;

  /**
   * Error reason
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

export class ProductResponseSuccessErrorBundles extends SpeakeasyBase {
  /**
   * Human-readable error message
   */
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;

  /**
   * Error reason
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

export class ProductResponseSuccess extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: ProductResponseSuccessErrorAttributes })
  @Expose({ name: "errorAttributes" })
  @Type(() => ProductResponseSuccessErrorAttributes)
  errorAttributes?: ProductResponseSuccessErrorAttributes[];

  @SpeakeasyMetadata({ elemType: ProductResponseSuccessErrorBundles })
  @Expose({ name: "errorBundles" })
  @Type(() => ProductResponseSuccessErrorBundles)
  errorBundles?: ProductResponseSuccessErrorBundles[];

  /**
   * Item ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "itemId" })
  itemId?: string;

  /**
   * Item ID, which increments sequentially
   */
  @SpeakeasyMetadata()
  @Expose({ name: "itemIdSeq" })
  itemIdSeq?: number;

  /**
   * Success message
   */
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;

  /**
   * Stock Keeping Unit (SKU) of item
   */
  @SpeakeasyMetadata()
  @Expose({ name: "sku" })
  sku?: string;
}

/**
 * OK
 */
export class ProductResponse extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: ProductResponseFailed })
  @Expose({ name: "failed" })
  @Type(() => ProductResponseFailed)
  failed?: ProductResponseFailed[];

  /**
   * List of item IDs
   */
  @SpeakeasyMetadata()
  @Expose({ name: "itemIds" })
  itemIds?: string[];

  @SpeakeasyMetadata({ elemType: ProductResponseSuccess })
  @Expose({ name: "success" })
  @Type(() => ProductResponseSuccess)
  success?: ProductResponseSuccess[];
}
