/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Internal server error
 */
export class ServerError extends SpeakeasyBase {
  /**
   * Error code
   */
  @SpeakeasyMetadata()
  @Expose({ name: "code" })
  code?: string;

  /**
   * Human-readable error description
   */
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;
}
