/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * OK
 */
export class SKUPage extends SpeakeasyBase {
  /**
   * 24-character system-generated category ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Human-readable numeric category ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * Human-readable numeric category ID, for external users
   */
  @SpeakeasyMetadata()
  @Expose({ name: "nodeId" })
  nodeId?: number;

  /**
   * Number of records (SKUs) per page
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pageSize" })
  pageSize?: number;

  /**
   * Number of pages for the given `pageSize`
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pages" })
  pages?: number;

  /**
   * SKUs of items belonging to this category.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "skus" })
  skus?: string[];

  /**
   * Total number of records
   */
  @SpeakeasyMetadata()
  @Expose({ name: "totalSize" })
  totalSize?: number;
}
