/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class UploadFileStatusResponse extends SpeakeasyBase {
  /**
   * Time of file upload (UTC format)
   */
  @SpeakeasyMetadata()
  @Expose({ name: "createdOn" })
  createdOn?: string;

  /**
   * URL to download uploaded CSV file.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "csvLink" })
  csvLink?: string;

  /**
   * URL to download import error file.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "errorCsv" })
  errorCsv?: string;

  /**
   * Name of CSV file
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * Upload status
   */
  @SpeakeasyMetadata()
  @Expose({ name: "statuses" })
  statuses?: any[];
}
