/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

/**
 * JSON object containing `channel`, `account`, `stage`, `date`, and `site` <br> .
 */
export class XSiteContext extends SpeakeasyBase {
  /**
   * 24 character client's co-pilot account ID. Mandatary only for multi-tenant clients (not for single tenant clients).
   */
  @SpeakeasyMetadata({ data: "header, name=account" })
  account?: string;

  /**
   * Sales channel. Mandatary for single and multi-tenant clients.
   */
  @SpeakeasyMetadata({ data: "header, name=channel" })
  channel?: number;

  /**
   * Localized date of endpoint execution. Mandatary for single and multi-tenant clients
   */
  @SpeakeasyMetadata({ data: "header, name=date" })
  date?: string;

  /**
   * Environment shared with the client during onboarding. Mandatary only for multi-tenant clients (not for single tenant clients).
   */
  @SpeakeasyMetadata({ data: "header, name=stage" })
  stage?: string;
}
