/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

/**
 * Status of category source. <br> **Note**: If omitted, 'ASSIGNED' status is used by default.
 */
export enum GetCategoriesNodeSourceExclusionsStatusEnum {
  Assigned = "ASSIGNED",
  Unassigned = "UNASSIGNED",
}

export class GetCategoriesNodeSourceExclusionsRequest extends SpeakeasyBase {
  /**
   * 24-character system-generated category ID. `id` and `nodeId` are the two identifiers of a category and one of them must be specified.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=id" })
  id?: string;

  /**
   * Human-readable numeric category ID. `id` and `nodeId` are the two identifiers of a category and one of them must be specified.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=nodeId",
  })
  nodeId?: number;

  /**
   * Page number to be retrieved. Applicable only in a paginated response and always paired with `size`.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=page" })
  page: number;

  /**
   * Number of records per page. Applicable only in a paginated response and always paired with `page`.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=size" })
  size: number;

  /**
   * Status of category source. <br> **Note**: If omitted, 'ASSIGNED' status is used by default.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=status",
  })
  status?: GetCategoriesNodeSourceExclusionsStatusEnum;

  /**
   * JSON object containing `channel`, `account`, `stage`, `date`, and `site` <br> .
   */
  @SpeakeasyMetadata({
    data: "header, style=simple;explode=false;name=x-site-context",
  })
  xSiteContext?: shared.XSiteContext;
}

export class GetCategoriesNodeSourceExclusionsResponse extends SpeakeasyBase {
  /**
   * Client error
   */
  @SpeakeasyMetadata()
  clientError?: shared.ClientError;

  @SpeakeasyMetadata()
  contentType: string;

  /**
   * OK
   */
  @SpeakeasyMetadata()
  nodeSourceExclusions?: shared.NodeSourceExclusions;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Internal server error
   */
  @SpeakeasyMetadata()
  serverError?: shared.ServerError;
}
