/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Type } from "class-transformer";

/**
 * Item status. <br> **Note**: <br> 1) Returns a paginated response. <br> 2) When used as the only criteria, must be paired with `size` and `page` to accommodate large data.
 */
export enum GetProductsStatusEnum {
  Active = "ACTIVE",
  Inactive = "INACTIVE",
}

export class GetProductsRequest extends SpeakeasyBase {
  /**
   * Lists items created after a specific date. Valid date formats are 'YYYY/MM/DD', 'YYYY-MM-DDTHH:mm:ss.SSSZ'. <br> **Note**: <br> 1) Applicable only when `skus` and `itemIds` are omitted <br> 2) Returns paginated response <br> 3) Must be paired with `size` and `page` to accommodate large data
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=createdAfter",
  })
  createdAfter?: string;

  /**
   * Lists items created before a specific date. Valid date formats are 'YYYY/MM/DD', 'YYYY-MM-DDTHH:mm:ss.SSSZ'. <br> **Note**: <br> 1) Applicable only when `skus` and `itemIds` are omitted <br> 2) Returns paginated response <br> 3) Must be paired with `size` and `page` to accommodate large data
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=createdBefore",
  })
  createdBefore?: string;

  /**
   * List of item IDs. Applicable only when `skus` are omitted. <br> **Note**: Either `skus` or `itemIds` can be used to get specific items. If they are omitted, all items are returned in a paginated response. As a result, `page` and `size` become mandatory to accommodate large data.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=false;name=itemIds",
  })
  itemIds?: number[];

  /**
   * Lists items modified after a specific date. Valid date formats are 'YYYY/MM/DD', 'YYYY-MM-DDTHH:mm:ss.SSSZ'. <br> **Note**: <br> 1) Applicable only when `skus` or `itemIds` are omitted <br> 2) Returns paginated response <br> 3) Must be paired with `size` and `page` to accommodate large data
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=modifiedAfter",
  })
  modifiedAfter?: string;

  /**
   * Gets items modified before a specific date. Valid date formats are 'YYYY/MM/DD', 'YYYY-MM-DDTHH:mm:ss.SSSZ'. <br> **Note**: <br> 1) Applicable only when `skus` and `itemIds` are omitted <br> 2) Returns paginated response <br> 3) Must be paired with `size` and `page` to accommodate large data
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=modifiedBefore",
  })
  modifiedBefore?: string;

  /**
   * Page number to be retrieved. Applicable only in a paginated response and always paired with `size`.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=page" })
  page?: number;

  /**
   * Number of records per page. Applicable only in a paginated response and always paired with `page`.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=size" })
  size?: number;

  /**
   * List of Stock Keeping Units (SKUs). <br> **Note**: Either `skus` or `itemIds` can be used to get specific items. If they are omitted, all items are returned in a paginated response. As a result, `page` and `size` become mandatory to accommodate large data.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=false;name=skus" })
  skus?: string[];

  /**
   * Item status. <br> **Note**: <br> 1) Returns a paginated response. <br> 2) When used as the only criteria, must be paired with `size` and `page` to accommodate large data.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=status",
  })
  status?: GetProductsStatusEnum;

  /**
   * JSON object containing `channel`, `account`, `stage`, `date`, and `site` <br> .
   */
  @SpeakeasyMetadata({
    data: "header, style=simple;explode=false;name=x-site-context",
  })
  xSiteContext?: shared.XSiteContext;
}

export class GetProductsResponse extends SpeakeasyBase {
  /**
   * Client error
   */
  @SpeakeasyMetadata()
  clientError?: shared.ClientError;

  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Internal server error
   */
  @SpeakeasyMetadata()
  serverError?: shared.ServerError;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * OK
   */
  @SpeakeasyMetadata()
  getProducts200ApplicationJSONOneOf?: any;
}
