/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Type } from "class-transformer";

/**
 * Category status. If omitted, returns a paginated response of categories in `ACTIVE` status. As a result, `page` and `size` becomes mandatory to support large data. <br> **Note**: When `type` is Primary, `status` must be Active. Inactive status is not applicable for Primary category.
 */
export enum SearchCategoriesStatusEnum {
  Active = "ACTIVE",
  Inactive = "INACTIVE",
  All = "ALL",
}

/**
 * Category type. <br> **Note**: If omitted, returns a paginated response with `ALL` categories. As a result, `page` and `size` becomes mandatory to support large data.
 */
export enum SearchCategoriesTypeEnum {
  Primary = "PRIMARY",
  Alternate = "ALTERNATE",
  All = "ALL",
}

export class SearchCategoriesRequest extends SpeakeasyBase {
  /**
   * List of 24-characters system-generated category IDs. If `ids` and `nodeIds` are omitted, this endpoint returns a paginated response. As a result, `page` and `size` becomes mandatory to accommodate large data.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=false;name=ids" })
  ids?: string[];

  /**
   * Keywords to search for categories. The response is paginated. As a result, `page` and `size` becomes mandatory to accommodate large data.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=keyword",
  })
  keyword?: string;

  /**
   * List of human-readable numeric category ID. If `ids` and `nodeIds` are omitted, this endpoint returns a paginated response. As a result, `page` and `size` becomes mandatory to accommodate large data.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=false;name=nodeIds",
  })
  nodeIds?: number[];

  /**
   * Page number to be retrieved. <br> **Note**: <br> 1) Applicable only in a paginated response.  <br> 2) Always paired with `size` <br> 3) No default value set. Unless a value is specified, endpoint returns an error.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=page" })
  page?: number;

  /**
   * Number of records per page <br> **Note**: <br> 1) Always paired with `page` <br> 2) Applicable only in a paginated response <br> 3) No default value set. Unless a value is specified, endpoint returns an error.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=size" })
  size?: number;

  /**
   * Category status. If omitted, returns a paginated response of categories in `ACTIVE` status. As a result, `page` and `size` becomes mandatory to support large data. <br> **Note**: When `type` is Primary, `status` must be Active. Inactive status is not applicable for Primary category.
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=status",
  })
  status?: SearchCategoriesStatusEnum;

  /**
   * Category type. <br> **Note**: If omitted, returns a paginated response with `ALL` categories. As a result, `page` and `size` becomes mandatory to support large data.
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=type" })
  type?: SearchCategoriesTypeEnum;

  /**
   * JSON object containing `channel`, `account`, `stage`, `date`, and `site` <br> .
   */
  @SpeakeasyMetadata({
    data: "header, style=simple;explode=false;name=x-site-context",
  })
  xSiteContext?: shared.XSiteContext;
}

export class SearchCategoriesResponse extends SpeakeasyBase {
  /**
   * OK
   */
  @SpeakeasyMetadata()
  categoryPage?: shared.CategoryPage;

  /**
   * Client error
   */
  @SpeakeasyMetadata()
  clientError?: shared.ClientError;

  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Internal server error
   */
  @SpeakeasyMetadata()
  serverError?: shared.ServerError;
}
